version: '3'
services:

  dsw-server:
    image: datastewardshipwizard/wizard-server:4.11
    platform: linux/amd64
    restart: always
    ports:
      - "3000:3000"  # Exposes port 3000 to all network interfaces
    depends_on:
      - postgres
      - minio
    volumes:
      - ./config/application.yml:/app/config/application.yml:ro
    extra_hosts:
      - host.docker.internal:host-gateway

  dsw-client:
    image: datastewardshipwizard/wizard-client:4.11
    restart: always
    ports:
      - "8080:8080"  # Exposes port 8080 to all network interfaces
    environment:
      API_URL: http://192.168.242.116:3000/wizard-api

  docworker:
    image: datastewardshipwizard/document-worker:4.11
    restart: always
    depends_on:
      - postgres
      - minio
      - dsw-server
    volumes:
      - ./config/application.yml:/app/config/application.yml:ro
    extra_hosts:
      - host.docker.internal:host-gateway

  mailer:
    image: datastewardshipwizard/mailer:4.11
    restart: always
    depends_on:
      - postgres
      - dsw-server
    volumes:
      - ./config/application.yml:/app/config/application.yml:ro

  postgres:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_DB: engine-wizard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  minio:
    image: minio/minio:RELEASE.2022-02-24T22-12-01Z
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # Exposes port 9000 to all network interfaces
      - "9001:9001"  # Exposes port 9001 to all network interfaces
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioPassword
